#!/bin/bash
# Create deployment package and show instructions

echo "╔════════════════════════════════════════════════════════╗"
echo "║  Hetzner Deployment Package Creator                   ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

# Create package
./create-deployment-package.sh

if [ $? -eq 0 ]; then
    echo ""
    echo "╔════════════════════════════════════════════════════════╗"
    echo "║  DEPLOYMENT INSTRUCTIONS                               ║"
    echo "╚════════════════════════════════════════════════════════╝"
    echo ""
    echo "Step 1: Upload to your Hetzner server"
    echo "---------------------------------------"
    echo ""
    echo "Replace YOUR_IP with your server IP address:"
    echo ""
    echo "  scp cyber-defense-deploy.tar.gz root@YOUR_IP:/root/"
    echo ""
    echo "Step 2: SSH to your server"
    echo "--------------------------"
    echo ""
    echo "  ssh root@YOUR_IP"
    echo ""
    echo "Step 3: Run these commands on the server"
    echo "----------------------------------------"
    echo ""
    echo "  cd /root"
    echo "  tar -xzf cyber-defense-deploy.tar.gz"
    echo "  cd cyber-defense"
    echo "  curl -fsSL https://get.docker.com | sh"
    echo "  apt-get install -y docker-compose jq"
    echo "  docker-compose up -d"
    echo "  docker logs -f ollama-init"
    echo ""
    echo "Wait for 'Qwen model ready!' then press Ctrl+C"
    echo ""
    echo "Step 4: Test it works"
    echo "---------------------"
    echo ""
    echo "  curl http://localhost:8000/health | jq"
    echo ""
    echo "Step 5: Access from your computer"
    echo "---------------------------------"
    echo ""
    echo "  Dashboard: http://YOUR_IP:3000"
    echo "  API: http://YOUR_IP:8000"
    echo ""
    echo "════════════════════════════════════════════════════════"
    echo ""
    echo "📚 Full guide: HETZNER_SIMPLE_DEPLOY.md"
    echo "⚡ Quick guide: HETZNER_ONE_LINER.md"
    echo ""
fi

